### ISSUE TITLE
Heap 시간초과

### ISSUE THREAD

**Issue by YoungJaeChoung** [YoungJaeChoung/Algorithm_ver.2#3]
heap_yj.py 

백준 사이트에서 시간 초과 남 

@choiking10

**Comment by yoon-zoyi** [comment]
넵 있다가 확인해보겠습니다.

**Comment by YoungJaeChoung** [comment]
와 바로 보이나보네요 ㅋㅋ 감사합니다:) 천천히 해주셔도 돼요! 일요일에 하셔도 돼구

**Comment by choiking10** [comment]
https://github.com/YoungJaeChoung/Algorithm_ver.2/blob/a209bfa4ff0a8e73eb8dc04a640e3f891d8cdb2f/study/heap_yj.py#L21
이부분 size* 3 혹은 *4로 해주는게 좋다고 말씀드렸습니다 수정 부탁드립니다. 

https://github.com/YoungJaeChoung/Algorithm_ver.2/blob/a209bfa4ff0a8e73eb8dc04a640e3f891d8cdb2f/study/heap_yj.py#L19-L24
https://github.com/YoungJaeChoung/Algorithm_ver.2/blob/a209bfa4ff0a8e73eb8dc04a640e3f891d8cdb2f/study/heap_yj.py#L43-L48
이런 방식으로 코딩하는 것은 좋지 않습니다. 함수 자체를 인자로 넘겨받으세요

**Comment by choiking10** [comment]
https://github.com/YoungJaeChoung/Algorithm_ver.2/blob/a209bfa4ff0a8e73eb8dc04a640e3f891d8cdb2f/study/heap_yj.py#L56-L68
이 부분은 로직 자체가 잘못됐습니다. 확인 부탁드립니다.
